### ISSUE TITLE
Duplicate Mails Sent

### ISSUE THREAD

**Issue by CG-root** [gophish/gophish#1242]
What version of Gophish are you using?:  0.7.1

Brief description of the issue:  Duplicate mails are sent

What are you expecting to see happen? :

What are you seeing happen? 
![duplicate](https://user-images.githubusercontent.com/25037744/47155853-6c8c8d00-d2ee-11e8-9893-3bb043d4b23a.jpeg)

We have sent phishing campaign to 800 e-mails. 700 of the, were sent twice flagged with "Email Sent" status, while 100 e-mails were sent once (as we excepted) but flagged as "Sending". attached screenshots.

Thanks,

**Comment by jordan-wright** [comment]
Hi @CG-root,

Thanks for reaching out! I'm sorry for any inconvenience this caused - this is definitely not intended behavior.

Is there any information you can provide, such as messages from the terminal that may indicate why the emails were sent twice? Or was there anything in your campaign configuration that's noteworthy (e.g. scheduling the campaign, or telling Gophish to spread out the emails)? Are there any events in your mail server that may suggest why the emails were received twice, such as a backoff being sent or something similar?

I see we have other issues such as #1223 or #1073 that suggest similar behavior, but I have yet to be able to reproduce it. 🙁

**Comment by CG-root** [comment]
Dear @jordan-wright 
The campaign was regular (no scheduling nor spread was made), the only thing we suspect is that once pressing the "Send Campaign" button, the browser was stuck for about 3-4 minutes (we using Edge), therefore we opened another browser tab to the platform from which we could see what's happening. Can this cause the glitch? 
Also we notice another strange behivor which that the status of e-mail that were sent once as expected was left "Sending" even-though we see the e-mail was sent:
![image](https://user-images.githubusercontent.com/25037744/47264045-c8d1f580-d516-11e8-8405-56f96fab9f51.png)
Hope this helps, please ask for any other information which can solve this mysteries glitch :)
Thanks!

**Comment by StrideTos1** [comment]
Dear @jordan-wright 

I have been having the same issue when running a campaign. The campaign would have no duplicate recipients/users uploaded in the Users/Groups tab for the campaign, but yet would have sent duplicate emails to a majority of the campaign.

I have run 4 campaigns (approx 700 users each time) with the version 0.7.1 and a majority received duplicate emails within the campaign. Have seen this issue occur a couple times in 0.5, but did not run into this issue with 0.3 or earlier.

Thank you.
TS

**Comment by StrideTos1** [comment]
Dear @jordan-wright 

I have been having the same issue when running a campaign. The campaign would have no duplicate recipients/users uploaded in the Users/Groups tab for the campaign, but yet would have sent duplicate emails to a majority of the campaign.

I have run 4 campaigns (approx 700 users each time) with the version 0.7.1 and a majority received duplicate emails within the campaign. Have seen this issue occur a couple times in 0.6, but did not run into this issue with 0.5 or 0.3.

Thank you.
TS

**Comment by jordan-wright** [comment]
I think I may have an idea as to what's causing this.

For a bit of background, Gophish keeps track of which emails to send out in a database table called `mail_logs`. When creating a new campaign, Gophish adds a row for every recipient.

Maillogs are processed in two ways by the `worker` package:

* Every minute, the worker picks up any outstanding maillogs to process (those with the `processing` column set to false. This is how scheduled campaigns and retries work.
* When a campaign is set to launch immediately, it's sent to a function that automatically grabs every maillog for a campaign and sends the email

Since we're seeing the symptoms on large campaigns, my guess is that a race condition is happening. Specifically, when Gophish starts to create the campaign and starts making maillogs, the minute-polling worker _happens_ to run, picking up some of the maillogs for processing, and sends out the emails.

Then, when the campaign is fully created, it's sent to the second worker which gets _all_ the maillogs for the campaign, sending the emails a second time.

I think there's a simple fix, which would be to lock the maillogs by default (set the `processing` column to true) when setting up the campaign. That way they aren't picked up by the polling worker.

Then, if we see that the campaign isn't set to launch immediately, we can unlock the logs for processing later on. That _should_ prevent any sort of race condition, preventing the duplicate emails. My guess is that the incorrect status is also probably a by-product of this happening so hopefully (🤞) this will fix that too.

Sorry about this inconvenience. This isn't how Gophish should operate, and I'll work to reproduce the issue to confirm my thinking and then get this fixed pronto.

**Comment by jordan-wright** [comment]
Just wanted to post an update on this one. I’m actively working to get this fixed, but it’s a bigger project than I thought.

I’m trying to do better about adding tests that reproduce the bugs we encounter. This is difficult to add tests for due to a couple of reasons:

* There is only one worker, defined at runtime. This means that I can’t make a mock worker that I could better control. I’m refactoring the way our servers are spun up to fix that issue.
* It’s a race condition based on time. This one will admittedly be more difficult. I don’t know that I have a great answer for this, since I don’t want to make a test that lasts a full minute, but I’m sure I’ll figure something out.

I appreciate y’alls patience with this. I’ll keep you all updated!

**Comment by mcvic1rj** [comment]
@jordan-wright I have not dug into the code, but isn't the simpler solution to not call the function that starts sending emails after the campaign is created?
This would cause a delay in the sending of email for ~1 minute but that shouldn't be too bad.

**Comment by jordan-wright** [comment]
@mcvic1rj that's how things used to be. If possible, though, I'd like to launch campaigns immediately if they're set to launch immediately. This gives a better user experience.

This would likely be a really simple fix as mentioned a couple of comments above. But since I'm trying to do a better job of writing tests for the things I've fixed, I'm doing some refactoring right now to make that possible. Things are moving along and it shouldn't be too much longer before a fix is published.

As a side note, this refactoring will make quite a few other things much easier down the line so it's time well spent 😄

**Comment by samsung42** [comment]
Any estimate to when this will be fixed?

Thanks!

**Comment by 3ldidi94** [comment]
Thanks for your work.
Just to add I am facing this issue each time I launch the GoPhish binary even if campaigns are mark as completed/finished

I can provide any logs or useful informations to you if needed in order to help you fixing this.

Is the fix mentionned above works ?

Thank you 👍 😄

**Comment by jordan-wright** [comment]
Hey everyone,

Sorry for the delay on this. The actual fix was small, but I used it as an opportunity to refactor some things in #1321.

This should be fixed now. I don't have an ETA on the next binary release yet, since there's still some things I want to add. In the meantime, it should work if you build from source.

Thanks for your patience!

**Comment by CG-root** [comment]
Issue still occurs.

**Comment by KiransHub** [comment]
sorry but yeah this still occurs. I raised a ticket only to have it marked dup and closed. Please can you do something about this? It's a major issue!

**Comment by jordan-wright** [comment]
Just to make sure, have you tried this with the latest master branch built from source? We haven’t released a binary build with the improvements yet.

**Comment by KiransHub** [comment]
Nope I’ve not tried this from source.  Can we just not have a build for this? I’m not a go dev and I want to make sure that we eliminate any potential issues. Kiran From: Jordan WrightSent: 17 December 2019 13:26To: gophish/gophishCc: KiransHub; CommentSubject: Re: [gophish/gophish] Duplicate Mails Sent (#1242) Just to make sure, have you tried this with the latest master branch built from source? We haven’t released a binary build with the improvements yet.> On Dec 17, 2019, at 7:05 AM, KiransHub <notifications@github.com> wrote:> > ﻿> sorry but yeah this still occurs. I raised a ticket only to have it marked dup and closed. Please can you do something about this? It's a major issue!> > —> You are receiving this because you modified the open/close state.> Reply to this email directly, view it on GitHub, or unsubscribe.—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dams3c** [comment]
Issue still occurs in latest version (0.12.1)

**Comment by dams3c** [comment]
Issue still occours in last version (0.12.1).
