### ISSUE TITLE
Copying campaign - Some fields no longer auto populate

### ISSUE THREAD

**Issue by IAMPi** [gophish/gophish#549]
Greetings, 

After the most recent upgrade i  now noticed that when copying a campaign the email and landing page template fields now automatically defaults to an early test email and test landing page templates. 

I deleted the test landing page and email template.  Now those fields no longer auto populate.  Is this behaviour intended?

**Comment by jordan-wright** [comment]
This tentatively sounds like the expected behavior. Previously, if you tried to copy items that are now deleted, the field would say "DELETED". Now, it's just blank since I didn't want to make "DELETED" an option in the dropdown.

**Comment by IAMPi** [comment]
So just to clarify cause I knew my first post was unclear when I wrote it :)

1) Upgrade gophish
2) Duplicate previous campaigns ...email and landing page fields populated with the same old test templates I had (not the correct one)
3) I delete the test templates....now when I duplicate the campaign the fields are blank
4) populate the duplicate campaign with the right email and landing page templace
5) send the campaign out
6) duplicate the duplicated campaign that I had sent out in step 5 
7) Fields are blank again

Hopefully that clarifies it...I can upload some images to clarify.

**Comment by jordan-wright** [comment]
Hey @IAMPi,

Thanks for the clarification! I'm still not sure what "same old test templates" means.

Could you upload some images to help us troubleshoot this?

Thanks!

**Comment by S0larflare** [comment]
Right, so I've just updated my test instance to the latest version to do some testing and I'm observing this too. If you create a campaign and then copy the campaign, the email template field doesn't autopopulate with the previous campaign's template, even if said template still exists. I've looked at the code and I can't work out why though, it seems to pass the template through the api call, it just doesn't put it in the field.

**Comment by jordan-wright** [comment]
I'm still having difficultly replicating this issue. When I duplicate a campaign, the email template and landing page fields are correctly populated for me. This is from the "Campaigns" page, right? Clicking on the "Copy Campaign" button?

**Comment by jmast01** [comment]
I am also experiencing this same issue after upgrading to version 0.3. When I choose to "Copy Campaign" for the most recent campaign from the Campaigns page. The Email Template, Landing Page, and Sending Profile values are populated with values from the very first two campaigns that still exist and were created over 4 months earlier. This is happening with campaigns that were created before the upgrade as well as new campaigns created after.

**Comment by jordan-wright** [comment]
It looks like @sjb-commarc was having the same issue in #1221. As mentioned earlier, I'm having significant issues reproducing this on my end.

If anyone is having this issue and would be willing to share their gophish.db with me (I understand if privacy concerns would prohibit you from doing so), you can email it to hi@getgophish.com and I would be happy to try and reproduce it there.

Otherwise, if anyone has information on how to reproduce this from a fresh Gophish install, I'd love to hear it so that we can track this down and get it resolved!

**Comment by jordan-wright** [comment]
Hey everyone!

I received a copy of a valid gophish.db file so I was able to reproduce the issue. Things should be fixed now. In a nutshell, it looks the ID of the item (template, landing page, etc.) was getting mangled by Select2, the library we're using to make the nice selection dropdowns.

This change should fix that 😄. If you build from source and can take this for a spin, please let me know if you continue to run into the issue!

**Comment by dsmurf** [comment]
dont know go language at all, so not simple at all.

**Comment by securitygeneration** [comment]
@jordan-wright I just compiled from source and the `copy campaign` button is still not working for me. Only the `URL` and `Sending Profile` fields copy correctly. I was going to create a new issue, but it may be simpler to reopen this one?
