### ISSUE TITLE
Problem of display in "New Group"

### ISSUE THREAD

**Issue by Cycl0pe** [gophish/gophish#904]
What version of Gophish are you using?:  V 0.4

Brief description of the issue: When adding a new user to fish in "New Group", there is a problem of display when the input is too long.

What are you expecting to see happen? : Perhaps,  a carriage return so the display of the new user to phish does not impinge out of the modal.

What are you seeing happen? The display of the new user impinge out of the modal

![test](https://user-images.githubusercontent.com/24911604/34515020-779df12c-f070-11e7-885d-ec274dd65685.png)

**Comment by jordan-wright** [comment]
What browser are you using?

Either way, thanks for reporting this. I'll see if I can fix this when I get a chance.

**Comment by Cycl0pe** [comment]
Hey,

Firefox 57.0.1!

Thanks

**Comment by shuheiktgw** [comment]
Let me work on this issue! 👍

**Comment by shuheiktgw** [comment]
Worked on this issue @ https://github.com/gophish/gophish/pull/915

**Comment by jordan-wright** [comment]
This was fixed in #915.

**Comment by Cycl0pe** [comment]
Hello Jordan,

I still have the same problem? Am I the only one with this problem?
